import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { signIn, signOut, useSession } from 'next-auth/client'

export default function Home() {

  const [ session, loading ] = useSession()

  return(
    <div className={styles.container}>
      <Head>
        <title>Auth App</title>
        <meta name="description" content="Generated by auth app" />
      </Head>

      <main className={styles.main}>
        <h1>This is the main</h1>
        {!session && <>
          Not signed in <br/>
          <button onClick={() => signIn()}>Sign in</button>
        </>}
        {session && <>
          Signed in as {session.user.email} <br/>
          <button onClick={() => signOut()}>Sign out</button>
        </>}
      </main>

      <footer className={styles.footer}>
        <a href="#">
          All right reserved by Developer Saap
        </a>
      </footer>
    </div>
  )
}
